name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Generate UML diagrams
        run: |
          mkdir -p output
          plantuml -o output mymy/diagram.puml

      - name: Upload diagrams
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: output

      - name: Commit and Push Generated Diagrams
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add mymy/output/*
          git commit -m "Add generated UML diagrams"
          git push

