name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # 리포지토리에 쓰기 권한 부여

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Generate UML diagrams
        run: |
          mkdir -p output
          plantuml -o output mymy/diagram.puml

      - name: Upload diagrams
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: output

      - name: Commit and Push Generated Diagrams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add mymy/output/*
          git commit -m "Add generated UML diagrams"
          git push
      - name: Debug output
         run: |
              ls -alh mymy/
            plantuml -o output mymy/diagram.puml
            ls -alh output/    
