name: Generate UML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: sudo apt-get update && sudo apt-get install -y plantuml

      - name: Generate UML diagrams
        run: |
          mkdir -p output
          plantuml -tpng -o output diagram.puml

      - name: Upload UML diagram
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagram
          path: output/*.png
